[package]
name = "daumdic"
version = "0.5.1"
authors = ["pbzweihander <sd852456@naver.com>"]
description = "Daum Dictionary API wrapper"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/daumdic/"
repository = "https://github.com/pbzweihander/daumdic-rs"
readme = "README.md"

[dependencies]
reqwest = "0.8"
failure = "0.1"
scraper = "0.7"
lazy_static = "1.0"
