[package]
name = "daumdic"
version = "0.3.0"
authors = ["pbzweihander <sd852456@naver.com>"]
description = "Daum Dictionary API wrapper"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/daumdic/"
repository = "https://github.com/pbzweihander/daumdic-rs"
readme = "README.md"

[features]
async = ["reqwest/unstable", "futures", "tokio-core"]

[dependencies]
reqwest = "0.8"
kuchiki = "0.7"
error-chain = "0.11"

futures = { version = "0.1", optional = true }
tokio-core = { version = "0.1", optional = true }
