[package]
name = "daumdic"
version = "0.2.1"
authors = ["pbzweihander <sd852456@naver.com>"]
description = "Daum Dictionary API"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/daumdic/"
repository = "https://github.com/pbzweihander/daumdic-rs"
readme = "README.md"

[dependencies]
reqwest = "0.8"
kuchiki = "0.6"
error-chain = "0.11"
